[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "swayfreq"
version = "2.0.0"
description = "Measure the frequency of a vibrating object using video data."
authors = [{name = "Joe Ammatelli"}]
license = {text = "MIT License"}